# Use official Nginx image
FROM nginx:alpine

# Copy only the contents of the browser folder to Nginx's serving directory
COPY dist/ui/browser /usr/share/nginx/html

# Copy a custom Nginx config file (optional)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
